version: '3.5'

services:
  zapp:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - zokrates
      - timber
    volumes:
      - ./build:/app/build
      - ./contracts/:/app/contracts/
      - ./.secret/:/app/.secret
      - ./migrations/:/app/migrations/
      - ./truffle-config.js:/app/truffle-config.js
      - ./circuits/:/app/circuits:delegated
      - ./proving-files/:/app/output:delegated # temporary solution to write-vk issue
      - ./orchestration/common/write-vk.mjs:/app/write-vk.mjs # "
      - ./orchestration/:/app/orchestration:delegated
      - ./test/:/app/test:delegated
      - ./config/:/app/config:delegated
    environment:
      BLOCKCHAIN_HOST: wss://rpc-mumbai.maticvigil.com/ws/v1/8bbba62057863e829094f78ba8d5b79bccb33e8b
      BLOCKCHAIN_PORT: 8545
    networks:
      - zapp_network

  zokrates:
    image: ghcr.io/eyblockchain/zokrates-worker-m1:v1.1
    # platform: linux/arm64/v8
    volumes:
      - ./circuits/:/app/circuits:delegated
      - ./proving-files/:/app/output:delegated
      - ./orchestration/common/write-vk.mjs:/app/write-vk.mjs
      - ./orchestration/common/db/:/app/orchestration/common/db:delegated
    environment:
      PROVING_SCHEME: 'g16'
    ports:
      - '8080:80'
    networks:
      - zapp_network

  zapp-setup:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - zokrates
    volumes:
      - ./config/:/app/config
      - ./.secret/:/app/.secret
      - ./circuits/:/app/circuits:delegated
      - ./contracts/:/app/contracts/
      - ./proving-files/:/app/output:delegated
      - ./orchestration/common/write-vk.mjs:/app/write-vk.mjs
      - ./orchestration/common/db/:/app/orchestration/common/db:delegated
      - ./orchestration/:/app/orchestration:delegated
    networks:
      - zapp_network

  timber:
    build: 
      context: https://github.com/EYBlockchain/timber.git#starlight/testnet:merkle-tree
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - timber-mongo
    volumes:
      - ./config/:/app/config
      #- ./.secret/:/app/.secret
      - ./contracts/:/app/contracts:consistent
      - ./build/:/app/build:consistent
    ports:
      - '9000:80'
    environment:
      HASH_TYPE: 'mimc'
      LOG_LEVEL: 'silly'
      UNIQUE_LEAVES: 'true'
      BLOCKCHAIN_HOST: wss://rpc-mumbai.maticvigil.com/ws/v1/8bbba62057863e829094f78ba8d5b79bccb33e8b
      BLOCKCHAIN_PORT: 8545
      CONTRACT_LOCATION: 'default'
      MONGO_HOST: mongodb://timber-mongo
      MONGO_PORT: 27017
      MONGO_NAME: merkle_tree
      MONGO_USERNAME: admin
      MONGO_PASSWORD: admin
    networks:
      - zapp_network

  #The database storing the merkle tree
  timber-mongo:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=merkle_tree
    volumes:
      - timber-mongo-volume:/data/db
    networks:
      - zapp_network

  deployer:
    build:
      context: .
      dockerfile: Dockerfile.polygondeployer
    volumes:
      - ./build:/app/build
      - ./.secret/:/app/.secret
      - ./contracts/:/app/contracts/
      - ./migrations/:/app/migrations/
      - ./truffle-config.js:/app/truffle-config.js
      - ./orchestration/:/app/orchestration:delegated
    environment:
      BLOCKCHAIN_HOST: wss://rpc-mumbai.maticvigil.com/ws/v1/8bbba62057863e829094f78ba8d5b79bccb33e8b
      BLOCKCHAIN_PORT: 8545
    networks:
      - zapp_network

volumes:
  timber-mongo-volume: {}

networks:
  zapp_network:
    name: zapp_network